# Generated by Django 5.1.2 on 2025-06-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_course_alter_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
    ]
