# Generated by Django 5.1.2 on 2025-06-12 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_title_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
    ]
